8name: Darts Schedule

on:
  schedule:
    # Weekly recurring schedules (March 6 to May 30, 2025)
    - cron: '0 18 * * 3' # 18:00 UTC Wednesdays
    - cron: '0 18 * * 4' # 18:00 UTC Thursdays
    - cron: '0 0 * * 5'  # 00:00 UTC Fridays
    - cron: '0 12 * * 5' # 12:00 UTC Fridays
  workflow_dispatch: # Allows manual triggering for testing

jobs:
  run-darts-script:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v4

      # Set up Python
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      # Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests supabase python-dotenv

      # Run the script with environment variables
      - name: Run darts script
        env:
          API_KEY: ${{ secrets.API_KEY }}
          NEXT_PUBLIC_SUPABASE_URL: ${{ secrets.NEXT_PUBLIC_SUPABASE_URL }}
          SUPABASE_SERVICE_ROLE_KEY: ${{ secrets.SUPABASE_SERVICE_ROLE_KEY }}
        run: |
          python darts_to_supabase.py

      # One-off runs for May 30 and May 31, 2025
      - name: Check and run one-off schedules
        if: |
          (github.event_name == 'schedule' && 
           (github.event.schedule == '0 18 30 5 *' || github.event.schedule == '0 12 31 5 *'))
        env:
          API_KEY: ${{ secrets.API_KEY }}
          NEXT_PUBLIC_SUPABASE_URL: ${{ secrets.NEXT_PUBLIC_SUPABASE_URL }}
          SUPABASE_SERVICE_ROLE_KEY: ${{ secrets.SUPABASE_SERVICE_ROLE_KEY }}
        run: |
          python darts_to_supabase.py
